In [4]:
!pip install gensim

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 2.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.6/60.6 kB 2.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 26.7/26.7 MB 54.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.3/18.3 MB 74.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 38.6/38.6 MB 15.5 MB/s eta 0:00:00
  Attempting uninstall: numpy
    Found existing installation: numpy 2.0.2
    Uninstalling numpy-2.0.2:
      Successfully uninstalled numpy-2.0.2
  Attempting uninstall: scipy
    Found existing installation: scipy 1.14.1
    Uninstalling scipy-1.14.1:
      Successfully uninstalled scipy-1.14.1


In [6]:
!pip install --upgrade --force-reinstall numpy gensim


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.0/62.0 kB 1.8 MB/s eta 0:00:00
  Using cached gensim-4.3.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (8.1 kB)
  Using cached numpy-1.26.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
  Using cached scipy-1.13.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (60 kB)
Using cached gensim-4.3.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (26.7 MB)
Using cached numpy-1.26.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.3 MB)
Using cached scipy-1.13.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (38.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.7/61.7 kB 3.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 83.2/83.2 kB 5.9 MB/s eta 0:00:00
  Attempting uninstall: wrapt
    Found existing installation: wrapt 1.17.2
    Uninstalling wrapt-1.17.2:
      Successfully uninstalled wrapt-1.17.2
  Attempting un

In [1]:
import gensim


In [2]:
from gensim.models import Word2Vec, KeyedVectors

In [4]:
import gensim.downloader as api
wv= api.load("glove-wiki-gigaword-50")
vec_king = wv['king']

In [5]:
vec_king

array([ 0.50451 ,  0.68607 , -0.59517 , -0.022801,  0.60046 , -0.13498 ,
       -0.08813 ,  0.47377 , -0.61798 , -0.31012 , -0.076666,  1.493   ,
       -0.034189, -0.98173 ,  0.68229 ,  0.81722 , -0.51874 , -0.31503 ,
       -0.55809 ,  0.66421 ,  0.1961  , -0.13495 , -0.11476 , -0.30344 ,
        0.41177 , -2.223   , -1.0756  , -1.0783  , -0.34354 ,  0.33505 ,
        1.9927  , -0.04234 , -0.64319 ,  0.71125 ,  0.49159 ,  0.16754 ,
        0.34344 , -0.25663 , -0.8523  ,  0.1661  ,  0.40102 ,  1.1685  ,
       -1.0137  , -0.21585 , -0.15155 ,  0.78321 , -0.91241 , -1.6106  ,
       -0.64426 , -0.51042 ], dtype=float32)

In [6]:
vec_king.shape

(50,)

In [7]:
wv['cricket']

array([-1.2233   , -0.28292  , -1.7429   ,  0.56621  , -0.13787  ,
       -0.88088  , -0.26887  ,  0.41893  ,  0.94977  , -0.61332  ,
        0.0092522,  1.0045   , -0.89004  , -0.55148  ,  0.61202  ,
        0.42256  ,  0.92935  ,  0.83307  , -1.5568   ,  0.084345 ,
       -0.018224 ,  0.84803  ,  0.68321  ,  0.97059  ,  0.26561  ,
       -1.0538   ,  0.40724  , -0.45079  , -0.89013  ,  0.94153  ,
        2.2055   ,  0.75363  ,  0.5166   ,  0.47977  ,  0.86824  ,
        0.57228  ,  0.81846  , -0.070934 , -0.9391   , -0.81628  ,
       -0.35486  , -0.010408 , -0.83316  ,  1.1001   , -0.087408 ,
        1.8452   , -0.83112  ,  0.43732  ,  0.63007  , -0.81023  ],
      dtype=float32)

In [8]:
wv.most_similar('cricket')

[('indies', 0.8089948296546936),
 ('twenty20', 0.8088222146034241),
 ('rugby', 0.8044811487197876),
 ('cricketers', 0.7978313565254211),
 ('england', 0.7800653576850891),
 ('wc2003', 0.7499521374702454),
 ('wc2003-wis', 0.7357773780822754),
 ('bowling', 0.7342497706413269),
 ('mcc', 0.7253372669219971),
 ('zealand', 0.7152737379074097)]

In [9]:
wv['happy']

array([ 0.092086,  0.2571  , -0.58693 , -0.37029 ,  1.0828  , -0.55466 ,
       -0.78142 ,  0.58696 , -0.58714 ,  0.46318 , -0.11267 ,  0.2606  ,
       -0.26928 , -0.072466,  1.247   ,  0.30571 ,  0.56731 ,  0.30509 ,
       -0.050312, -0.64443 , -0.54513 ,  0.86429 ,  0.20914 ,  0.56334 ,
        1.1228  , -1.0516  , -0.78105 ,  0.29656 ,  0.7261  , -0.61392 ,
        2.4225  ,  1.0142  , -0.17753 ,  0.4147  , -0.12966 , -0.47064 ,
        0.3807  ,  0.16309 , -0.323   , -0.77899 , -0.42473 , -0.30826 ,
       -0.42242 ,  0.055069,  0.38267 ,  0.037415, -0.4302  , -0.39442 ,
        0.10511 ,  0.87286 ], dtype=float32)

In [10]:
wv.most_similar('happy')

[("'m", 0.9142323136329651),
 ('everyone', 0.8976402282714844),
 ('everybody', 0.8965489864349365),
 ('really', 0.88397616147995),
 ('me', 0.8784631490707397),
 ('definitely', 0.8762788772583008),
 ('maybe', 0.8756702542304993),
 ("'d", 0.8718011975288391),
 ('feel', 0.8707678318023682),
 ('i', 0.8707453012466431)]

In [11]:
vec= wv['king']-wv['man']+wv['woman']

In [12]:
vec

array([ 0.41736597,  0.90427005, -1.0050299 , -0.06202102,  0.49725997,
        0.80667007, -0.14855   ,  0.80365   , -0.15653998, -0.66973996,
        0.23435399,  0.62476   ,  0.925871  , -0.97099996,  0.92566   ,
        0.89915   , -1.54596   , -0.52625   ,  0.13695401,  0.66199005,
        0.4871601 ,  0.37035   , -0.214214  ,  0.10100996,  0.71358   ,
       -2.0874999 , -1.1362001 , -1.1496099 , -0.53599   ,  0.27389997,
        1.6723    ,  0.02930999, -0.77656007,  0.46056286,  0.34866   ,
       -0.05741701,  0.19444   , -0.207748  , -0.73038995, -0.10751998,
        0.235544  ,  0.96423995, -0.46993998, -0.48727497, -0.25399995,
        0.4621299 , -0.66081   , -1.9451499 , -0.68797004, -0.49784005],
      dtype=float32)

In [13]:
wv.most_similar([vec])

[('king', 0.8859834671020508),
 ('queen', 0.8609582185745239),
 ('daughter', 0.7684512734413147),
 ('prince', 0.7640699744224548),
 ('throne', 0.7634970545768738),
 ('princess', 0.7512729167938232),
 ('elizabeth', 0.7506489157676697),
 ('father', 0.7314497232437134),
 ('kingdom', 0.7296158671379089),
 ('mother', 0.728001058101654)]

Word2Vec is an NLP technique that transforms words into vector representations based on their context in a sentence. Using Gensim and pre-trained models like GloVe, we can find word similarities, perform analogies (e.g., king - man + woman = queen), and explore word relationships effectively.